import React, { PropsWithChildren, FC } from "react";
import { Box, Grid, GridItem, useBreakpointValue } from "@chakra-ui/react";
import Head from 'next/head'

import { Navbar } from "@root/components/navigation/Navbar";
import { Sidebar } from "@root/components/navigation/Sidebar";
import { MobileNavbar } from "@root/components/navigation/MobileNavbar";

interface PageProps extends React.HTMLAttributes<HTMLDivElement> {
}

export const Page = ({children}: PageProps) => {
  const isMobile = useBreakpointValue(
    {
      base: true,
      sm: true,
      md: false,
      lg: false,
    },
    {
      ssr: true,
    }
  );

  return (
    <>
        <Head>
            <title>SaaS UI Template</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {isMobile ? (
        <MobileNavbar />
      ) : (
        <Navbar />
      )}

      <Grid templateColumns={{ base: "1", md: "280px 1fr" }}>
        {!isMobile && (
          <GridItem>
            {/* {/* <Sidebar />  */}
          </GridItem>
        )} 

        <GridItem
          minHeight='100vh'
          w='100%'
          my='25px'
          mb='4rem'
          px={{ base: "24px", md: "40px" }}
          overflowX='hidden'
        >
          {children}
        </GridItem>
      </Grid>
    </>
        
  )
}