import React from 'react'
import Head from 'next/head'

interface PageProps extends React.HTMLAttributes<HTMLDivElement> {
}

export const Page = ({children}: PageProps) => {
  return (
    <>
        <Head>
            <title>SaaS UI Template</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
            {children}
        </main>
    </>
        
  )
}